// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyCcSjVMIQanDCxaoaxv9YXPPX7D40qkzV8',
    appId: '1:785304744759:web:c321839940368ba9f160b2',
    messagingSenderId: '785304744759',
    projectId: 'my-portfolio-website-1264a',
    authDomain: 'my-portfolio-website-1264a.firebaseapp.com',
    storageBucket: 'my-portfolio-website-1264a.firebasestorage.app',
    measurementId: 'G-PCTYEVEZ8S',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyD2mUYoEnLMxQBtCyTxWcggRiaR896AWU4',
    appId: '1:785304744759:android:b2cae7dff305ff96f160b2',
    messagingSenderId: '785304744759',
    projectId: 'my-portfolio-website-1264a',
    storageBucket: 'my-portfolio-website-1264a.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyBoLVtBXIfiPL2d63R2wzj9V8eDakao0a4',
    appId: '1:785304744759:ios:e9f4552b722896ddf160b2',
    messagingSenderId: '785304744759',
    projectId: 'my-portfolio-website-1264a',
    storageBucket: 'my-portfolio-website-1264a.firebasestorage.app',
    iosBundleId: 'com.example.rolloPortfolio',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyBoLVtBXIfiPL2d63R2wzj9V8eDakao0a4',
    appId: '1:785304744759:ios:e9f4552b722896ddf160b2',
    messagingSenderId: '785304744759',
    projectId: 'my-portfolio-website-1264a',
    storageBucket: 'my-portfolio-website-1264a.firebasestorage.app',
    iosBundleId: 'com.example.rolloPortfolio',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyCcSjVMIQanDCxaoaxv9YXPPX7D40qkzV8',
    appId: '1:785304744759:web:567eb16e35868cfef160b2',
    messagingSenderId: '785304744759',
    projectId: 'my-portfolio-website-1264a',
    authDomain: 'my-portfolio-website-1264a.firebaseapp.com',
    storageBucket: 'my-portfolio-website-1264a.firebasestorage.app',
    measurementId: 'G-KEFR8ZYCFM',
  );
}
